### ISSUE TITLE
Add ability to provide custom signal to a running application

### ISSUE THREAD

**Issue by seregazhuk** [seregazhuk/php-watcher#25]
Currently, when the watcher restarts the script it always sends `SIGTERM`. We need to customize it and allow it to send any signal. Make it customizable via config `signal`:

```yml
watch:
  - src
  - config
signal: SIGINT
```

or in a command line:

```bash
php-watcher server.php --signal SIGINT
```
